; Planta RC: pino 3 = sinal/alimentacao PWM (0..100% duty), A0 = leitura de
; tensao no capacitor (0..5V, AREF padrao, sem divisor). N=1, M=1.

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../../lib
